#!/bin/sh
# https://github.com/github/scripts-to-rule-them-all

# Sets the project back to its initial state.
# Should be run the first time the repo is pulled
# or if you want to reset the project to its
# initial state.

script/bootstrap

rake db:drop
rake db:create
rake db:migrate